version: "2"

services:
 mysqldb:
   image: mysql:5.7
   container_name: db
   restart: always
   environment:
     - MYSQL_DATABASE: achatdb
     - MYSQL_ALLOW_EMPTY_PASSWORD: yes
   ports:
      - "3306:3306"
   volumes:
      - db:/var/lib/mysql
 app:
   image: nourmanai/imagedev
   container_name: imagedev
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
   
    
 

volumes:
 db:
