version: '3'
services:
 
 mysqldb:
  image: mysql
  container_name: db
  
  environment:
   MYSQL_DATABASE: 'achatdb'
   MYSQL_ROOT_PASSWORD: ''
  ports:
   - '3306:3306'
  volumes:
   - db:/var/lib/mysql
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: mysqldb
  depends_on:
  - mysqldb
  ports:
   - '8068:81'
 spring_app:
  image: nourmanai/achat
  container_name: imagedev
  restart: on-failure
  ports:
   - 8089:8089
  depends_on:
   - mysqldb
  volumes:
   - achat_cache:/achatapp-cache



volumes:

 db:
 achat_cache:
